name: Youtube Music - Hirotoshi Uchida (1st) from hearthis.at
uses: lowlighter/metrics@latest
with:
  token: NOT_NEEDED
  base: ""
  plugin_music: yes
  plugin_music_playlist: >-
    https://music.youtube.com/playlist?list=PLOpvGdVAd0oh3urHCS8C_rtpgDAdAeld2&si=K0l3Waqm_GVtQZBe
