name: Youtube Music - Hirotoshi Uchida (1st) from hearthis.at
on:
  # run automatically every 5 minutes
  schedule:
    - cron: "*/5 * * * *" 
  # allows to manually run the job at any time
  workflow_dispatch:
  # run on every push on the master branch
  push:
    branches:
    - main
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      -name: published youtube music
       uses: lowlighter/metrics@latest
       with:
         token: NOT_NEEDED
         base: ""
         plugin_music: yes
         plugin_music_playlist: >-
           https://music.youtube.com/playlist?list=PLOpvGdVAd0oh3urHCS8C_rtpgDAdAeld2&si=K0l3Waqm_GVtQZBe
