name: Youtube Music - Hirotoshi Uchida (2nd) from hearthis.at
uses: lowlighter/metrics@latest
with:
  token: NOT_NEEDED
  base: ""
  plugin_music: yes
  plugin_music_playlist: >-
    https://music.youtube.com/playlist?list=PLOpvGdVAd0oip9LjI9fPdyUxk218BMhFQ&si=Hvk2i_Lk4L1Lw9i_
